### PR TITLE
confirm / dialog

### PR DESCRIPTION
**Pull request by jmervine**
see #31 for full desc

@jdorfman please play with this and toss me some feedback

todo:
- [x] example?
- [x] usage
- [x] docs
- [x] version bump `1.1.0`
- [x] update url from `https://maxcdn.github.io/shml/` to http://shml.xyz
- [ ] Git tag

Post-release:
- [ ] Update Homebrew
- [ ] Update npm
- [ ] Tweet

### CODE REVIEW

**Comment by jmervine** [comment]
I'm going to need to totally refactor tests after the last changes. I'll look at that tonight.

**Comment by jmervine** [comment]
@jdorfman fixed tests and added usage, not sure if you want to include experimental stuff in the docs yet, but I don't suppose it's a blocker for merging to master... your call... merge if you're happy.

**Comment by jdorfman** [comment]
I'm happy. Only took me 2 years ;)

**Comment by jmervine** [comment]
@jdorfman Started with a rebase of master to kick this off again.

**Comment by jmervine** [comment]
@jdorfman I'm going to leave it to you to update the documentation.

**Pull request merged**
